--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13
-- Dumped by pg_dump version 15.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: adocao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.adocao (
    id bigint NOT NULL,
    data_adocao date,
    cliente_id bigint,
    pet_id bigint
);


ALTER TABLE public.adocao OWNER TO postgres;

--
-- Name: adocao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.adocao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.adocao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: adocao_pets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.adocao_pets (
    adocao_id bigint NOT NULL,
    pets_id bigint NOT NULL
);


ALTER TABLE public.adocao_pets OWNER TO postgres;

--
-- Name: formulario_adocao; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.formulario_adocao (
    id bigint NOT NULL,
    ambiente character varying(255),
    ambiente_seguro boolean NOT NULL,
    email character varying(255),
    espaco_externo boolean NOT NULL,
    motivo character varying(255),
    telefone character varying(255),
    teve_animais_antes boolean NOT NULL,
    client_id bigint,
    pet_id bigint
);


ALTER TABLE public.formulario_adocao OWNER TO postgres;

--
-- Name: formulario_adocao_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.formulario_adocao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formulario_adocao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pets (
    id bigint NOT NULL,
    descricao character varying(255),
    foto_url character varying(255),
    idade character varying(255),
    nome character varying(255),
    porte character varying(255),
    raca character varying(255),
    status character varying(255),
    tipo character varying(255),
    owner_id bigint,
    localizacao character varying(255),
    CONSTRAINT pets_status_check CHECK (((status)::text = ANY ((ARRAY['Disponivel'::character varying, 'Adotado'::character varying])::text[])))
);


ALTER TABLE public.pets OWNER TO postgres;

--
-- Name: pets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.refresh_token (
    id bigint NOT NULL,
    expiry timestamp(6) with time zone NOT NULL,
    revoked_at timestamp(6) with time zone,
    token character varying(255) NOT NULL,
    user_id bigint
);


ALTER TABLE public.refresh_token OWNER TO postgres;

--
-- Name: refresh_token_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.refresh_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuario; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuario (
    id bigint NOT NULL,
    email character varying(255),
    name character varying(255),
    password character varying(255),
    role character varying(255),
    CONSTRAINT usuario_role_check CHECK (((role)::text = ANY ((ARRAY['Anunciante'::character varying, 'Adotante'::character varying])::text[])))
);


ALTER TABLE public.usuario OWNER TO postgres;

--
-- Name: usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: adocao adocao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adocao
    ADD CONSTRAINT adocao_pkey PRIMARY KEY (id);


--
-- Name: formulario_adocao formulario_adocao_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formulario_adocao
    ADD CONSTRAINT formulario_adocao_pkey PRIMARY KEY (id);


--
-- Name: pets pets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pets
    ADD CONSTRAINT pets_pkey PRIMARY KEY (id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (id);


--
-- Name: usuario uk5171l57faosmj8myawaucatdw; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT uk5171l57faosmj8myawaucatdw UNIQUE (email);


--
-- Name: adocao ukmo7vk1m38hf34u9s33hegykj7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adocao
    ADD CONSTRAINT ukmo7vk1m38hf34u9s33hegykj7 UNIQUE (pet_id);


--
-- Name: refresh_token ukr4k4edos30bx9neoq81mdvwph; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT ukr4k4edos30bx9neoq81mdvwph UNIQUE (token);


--
-- Name: usuario usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuario
    ADD CONSTRAINT usuario_pkey PRIMARY KEY (id);


--
-- Name: formulario_adocao fk29bm01myxy3svnamvqiuted0a; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formulario_adocao
    ADD CONSTRAINT fk29bm01myxy3svnamvqiuted0a FOREIGN KEY (pet_id) REFERENCES public.pets(id);


--
-- Name: pets fk59ht17kxc0wa2cu7dn15hjks0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pets
    ADD CONSTRAINT fk59ht17kxc0wa2cu7dn15hjks0 FOREIGN KEY (owner_id) REFERENCES public.usuario(id);


--
-- Name: adocao fkaxm2e7k4hwe3advuchrriqole; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adocao
    ADD CONSTRAINT fkaxm2e7k4hwe3advuchrriqole FOREIGN KEY (cliente_id) REFERENCES public.usuario(id);


--
-- Name: adocao fkbrgpmtahgb9u95r9199e7o4it; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adocao
    ADD CONSTRAINT fkbrgpmtahgb9u95r9199e7o4it FOREIGN KEY (pet_id) REFERENCES public.pets(id);


--
-- Name: refresh_token fkenvguqmt5g4sywplefd88osg; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT fkenvguqmt5g4sywplefd88osg FOREIGN KEY (user_id) REFERENCES public.usuario(id);


--
-- Name: adocao_pets fkfeypynflgwnt71ij6gk4vmb9r; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adocao_pets
    ADD CONSTRAINT fkfeypynflgwnt71ij6gk4vmb9r FOREIGN KEY (pets_id) REFERENCES public.pets(id);


--
-- Name: adocao_pets fklh5aoip1enmeosu9j7192qlc5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.adocao_pets
    ADD CONSTRAINT fklh5aoip1enmeosu9j7192qlc5 FOREIGN KEY (adocao_id) REFERENCES public.adocao(id);


--
-- Name: formulario_adocao fkmg069t6du92b2u4vgohhrd0d4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.formulario_adocao
    ADD CONSTRAINT fkmg069t6du92b2u4vgohhrd0d4 FOREIGN KEY (client_id) REFERENCES public.usuario(id);


--
-- PostgreSQL database dump complete
--

